---

- include: dist_vars.yml

- name: Install required packages
  package:
    name: "{{ item }}"
    state: "present"
  with_flattened:
    - "{{ snmpd_packages }}"

- name: Create user and group
  include: user.yml
  when: snmpd_create_user

- name: Configure lldpd daemon variables
  template:
    src: 'etc/default/lldpd.j2'
    dest: '/etc/default/lldpd'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: Restart lldpd
  when: snmpd_lldpd is defined and snmpd_lldpd

- name: Check if /etc/snmp/ exists
  file: path=/etc/snmp state=directory

- name: Configure snmpd daemon variables
  template:
    src: 'etc/default/snmpd.j2'
    dest: '/etc/default/snmpd'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: Restart snmpd
  when: snmpd_create_daemon_variables

- name: Configure snmpd service
  template:
    src: 'etc/snmp/snmpd.conf.j2'
    dest: '/etc/snmp/snmpd.conf'
    owner: 'root'
    group: 'root'
    mode: '0600'
  notify: Restart snmpd

- name: Enable snmpd
  service:
    name: "snmpd"
    enabled: true
  when: snmpd_start_service

- name: Enable lldpd
  service:
    name: "lldpd"
    enabled: true
  when: snmpd_lldpd is defined and snmpd_lldpd
