---

- name: Include distribution specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "vars/{{ ansible_distribution }}.yml"
      skip: true

- name: Include release specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "vars/{{ ansible_distribution_release }}.yml"
      skip: true

- name: Install required packages
  package:
    name: "{{ item }}"
    state: "present"
  with_flattened:
    - "{{ snmpd_packages }}"

- name: Configure lldpd daemon variables
  template:
    src: 'etc/default/lldpd.j2'
    dest: '/etc/default/lldpd'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: [ 'Restart lldpd' ]
  when: snmpd_lldpd is defined and snmpd_lldpd

- name: Check if /etc/snmp/ exists
  file: path=/etc/snmp state=directory

- name: Configure snmpd daemon variables
  template:
    src: 'etc/default/snmpd.j2'
    dest: '/etc/default/snmpd'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: [ 'Restart snmpd' ]

- name: Configure snmpd service
  template:
    src: 'etc/snmp/snmpd.conf.j2'
    dest: '/etc/snmp/snmpd.conf'
    owner: 'root'
    group: 'root'
    mode: '0600'
  notify: [ 'Restart snmpd' ]

- name: Enable snmpd
  service:
    name: "snmpd"
    enabled: yes

- name: Enable lldpd
  service:
    name: "lldpd"
    enabled: yes
  when: snmpd_lldpd is defined and snmpd_lldpd
