---

- name: Check if snmpd is installed
  environment:
    LC_MESSAGES: 'C'
  command: dpkg-query -W -f='${Version}\n' snmpd
  register: snmpd_register_version
  changed_when: False
  failed_when: False

- name: Install required packages
  apt:
    name: '{{ item }}'
    state: 'present'
    install_recommends: False
  with_flattened:
    - [ 'snmp', 'snmpd' ]
    - [ '{{ "lldpd" if snmpd_lldpd else [] }}' ]
    - snmpd_packages

- name: Configure lldpd daemon variables
  template:
    src: 'etc/default/lldpd.j2'
    dest: '/etc/default/lldpd'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: [ 'Restart lldpd' ]
  when: snmpd_lldpd is defined and snmpd_lldpd

- name: Configure snmpd daemon variables
  template:
    src: 'etc/default/snmpd.j2'
    dest: '/etc/default/snmpd'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: [ 'Restart snmpd' ]

- name: Configure snmpd service
  template:
    src: 'etc/snmp/snmpd.conf.j2'
    dest: '/etc/snmp/snmpd.conf'
    owner: 'root'
    group: 'root'
    mode: '0600'
  notify: [ 'Restart snmpd' ]
