---

- name: Restart snmpd
  service:
    name: 'snmpd'
    enabled: true
    state: 'restarted'
  when: snmpd_start_service

- name: Restart lldpd
  service:
    name: 'lldpd'
    state: 'restarted'

# vim: set ts=2 sw=2:
