---
dependency:
  name: galaxy
driver:
  name: docker
ansible:
  verbose: vv

provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
  inventory:
    group_vars:
      no_service:
        snmpd_start_service: false

platforms:
  - name: ansible-ubuntu-16-04-lts
    image: ubuntu:16.04
  - name: ansible-ubuntu-18-04-lts
    image: ubuntu:18.04
  - name: ansible-ubuntu-lts
    image: ubuntu:20.04
  - name: ansible-debian
    image: debian:latest
  - name: ansible-alpine
    image: alpine:latest
    command: bash -c 'while true; do sleep 5; done'
    groups:
      - os_alpine
      - no_service
  - name: ansible-arch
    image: archlinux/base:latest
    command: /usr/lib/systemd/systemd
    privileged: true
  - name: ansible-fedora
    image: fedora:latest
  - name: ansible-centos
    image: centos:latest
    command: /usr/lib/systemd/systemd
    privileged: true

scenario:
  name: default
verifier:
  name: ansible
