---
- name: Prepare alpine
  hosts: os_alpine
  tasks:
    - name: Install openrc
      apk:
        name: "openrc"
        update_cache: true

- name: Update apt
  hosts: apt
  tasks:
    - name: Update cache
      apt:
        update_cache: true
        upgrade: true
